### PR TITLE
Main review component mocked

### PR DESCRIPTION
**Pull request by Nick-Zabalza**
@GrumpyCat0709  @margotTenenbaum 

Finally finished my first feature. A lot of work went into it and you will notice quite the amount of new codebase. However, as the title of this PR suggests, most of what is in this push is a mocked-out component. As such, most of the codebase will eventually be stripped out and updated and so I wouldn't spend too much time code reviewing.

A prime example of this is how I mocked everything out using <div> tags. Many of those will end up being replaced with things like <span>, <a>, <table>, etc later.

You can also tell most of the codebase is relatively unimportant by the fact that I only felt one test was necessary for this PR: to test if uppermost parent component mounts or not.

What I feel the major accomplishments are for this PR:
1. Further set up environment with more advanced webpack config options, linter and advanced linter options, and test environment
2. Fairly well mocked out service component as can be seen when running the index.html file in the browser (see ReadMe for more info)
3. Uppermost component mounts to DOM, with libraries such as React, Redux, etc loaded via CDN.

Instructions for seeing component in browser and tests in browser can be found in ReadMe.

### CODE REVIEW

**Comment by margotTenenbaum** [comment]
@Nick-Zabalza 
Hi Nick,
Great job with this setup so far. Excellent attention to detail with each react component, and good use of components like Helpful to keep the code dry. I compared the page layout to PetCo's website and everything looks like it's in the right place.

1. One small detail. In the highlightedReviews component, it looks like the PetCo website has a link to "Show Full Review" after the first sentence or so of the review (it looks like approx 21 words in, the review is cut off with ...) but I don't see this button mocked out in your component.

2. On both the Spec Runner and Reviews Service pages, I got a console warning about DevTools not being able to load content for momentjs (404 error). This may not be important but just wanted to mention.

Great work! Looking forward to seeing the next iteration.

**Comment by Nick-Zabalza** [comment]
@margotTenenbaum 

Thanks for the feedback Elizabeth. Basically sounds like my PR is ready for merging. I say this because:

1. I also saw the Show Full Review feature, plus a few more I didn't include, because I felt I was already doing enough theorycrafting as it was. For the Show Full Review featue in particular, I didn't want to theorycraft it because I've never implemented a feature like that and so didn't have enough prior knowledge to draw upon. if you want, i can try theorycrafting it. Otherwise, I was just planning on waiting until working on its parent component, before giving it serious consideration.

2. I checked and the actual moment library is being added and accessible from the global window object. And it works when I try to use it. The warning seems to most likely involve how the minified version was packaged. For some reason, it expects to have a source map but, usually when you minify something for production, you don't include a source map. Weird error but nothing that interferes with anything.

Do you agree these issues are either non-issues or issues I can resolve later? Should I merge this?

**Comment by margotTenenbaum** [comment]
@Nick-Zabalza 
I agree, you're ready to merge!

**Comment by Nick-Zabalza** [comment]
Thanks, Elizabeth!

**Pull request merged**
